[package]
name = "repaint-with-piet-svg" # TODO rename to repaint-with-piet because it should not be specific to svg
version = "0.1.0"
edition = "2021"

[dependencies]
piet = "0.6.2"
repaint = { version = "0.1.0", path = "../../repaint" }

[dev-dependencies]
piet-svg = "0.6.2"
